language: node_js
node_js:
  - 12.16.2
before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_API_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: npm run publish:packages
